Fix issues during container VM bootstrap
Delete the /etc/localtime file that shows in centos:6.9 based
bootstrap, causing the system clock to be set to EDT, but interpreted as
UTC after the switch to the container filesystem.

Stop the udev daemon after hardware has been initialized and before
switching to the container filesystem. This is done because the udev rules
will almost certainly not be present after the switch_root.
If hotadd is ever required then the rules will have to be added to
/.tether and udev configured to read from that tree while managing /dev.

Restore the important vsyscall option to the bootloader kernel
options, along with the others that were dropped.
Adds rgnd to the tmpfs size calculation.

Allow a repo config to specify specific kernel modules to be loaded
during the existing modprobe pass.
This was done to allow for modules that do not exist or have had name
changes between different kernel versions/vendors.

Also adds explicit load of xt_state module for iptables.

For some reason busybox based images were not correctly demand loading
xt_state module. All other images seemed to have no problem.
The failure was resulting in a failure to enable iptables configuration
for established connection tracking (which is the first rule applied to
the VIC chain and uses the xt_state module) and that prevented any
subsequent rules from being set, resulting in no outbound rule. This is
seen as "operation not permtted" error from ping, as an example.

Bring up loopback interface since systemd is not called for init. Package
net-tools conflicts with toybox so use ifconfig to bring up lo.

The tether explicitly logs to both stdout/stderr and to the serial debug
port. This change redirects stdout/stderr to the console so that we do not
end up with duplicate lines in the serial log. The stdout/stderr are
redirected to the serial log directly during bootstrap in order to log the
initializtion script output before the switch_root to tether.

The udevd in centos-6.9 (other distros unconfirmed) does not create the
symlink /dev/fd->/proc/self/fd. This results in various images (postgres
specifically) reporting errors such as:
initdb: could not open file "/dev/fd/63" for reading: No such file or
directory

The /dev/pts entries should be owned by group "tty" (gid=5) as has been
the convention for many years.
Likewise /dev/pts/ptmx should be mode 666 to allow creation of additional
pty device pairs.

Mount cgroups to support DCH. In some distro with older kernel version,
like centos6, cgroup is not mounted on /sys/fs/cgroup but on /cgroup,
in which case, we would not use cgroup. Now we test this directory's
existence before mounting it to prevent error message.

diff --git a/isos/bootstrap/bootstrap b/isos/bootstrap/bootstrap
--- a/isos/bootstrap/bootstrap
+++ b/isos/bootstrap/bootstrap
@@ -6,23 +6,21 @@ echo 1 > /proc/sys/net/ipv4/conf/all/arp_notify
 echo 1 > /proc/sys/net/ipv4/conf/default/arp_notify
 
 # depending on kernel, some may already be loaded or built in
+# this appends to any defined in a "drivers" arayy via repo customizations
 echo "Loading drivers"
-drivers=( \
+drivers+=( \
     "vmw_pvscsi" \
     "vmxnet3" \
 	"nfnetlink" \
 	"iptable_filter" \
 	"xt_conntrack" \
-    "nf_nat_redirect" \
-    "xt_REDIRECT" \
     "nf_nat_ipv4" \
     "iptable_nat" \
 	"nf_conntrack" \
 	"nf_conntrack_ipv4" \
 	"nf_defrag_ipv4" \
 	"ipt_REJECT"\
-	"nf_reject_ipv4"\
-	"nfsv3" \
+	"xt_state" \
 )
 
 
@@ -107,21 +105,36 @@ if timeout -s KILL 2m mount -t ext4 /dev/disk/by-label/containerfs ${MOUNTPOINT}
     # TEMP: https://github.com/vmware/vic/issues/6279
     echo 262144 > /proc/sys/vm/max_map_count
 
-    until [[ $(ls -1 /dev/disk/by-label | wc -l) -eq $(ls -1 /sys/block | grep -v ram | grep -v loop | wc -l) ]]; do sleep 0.1;done
+    # mount the cgroup hierarchy to allow DinV
+    if [ -d /sys/fs/cgroup ];then
+        mount -t cgroup -o all cgroup /sys/fs/cgroup
+    fi
+
+    until [[ $(ls -1 /dev/disk/by-label | wc -l) -eq $(ls -1 /sys/block/ | grep -v 'loop*' | grep -v 'ram*' | wc -l) ]]; do sleep 0.1;done
+
+    # stop udevd if we've recorded the pid to be removed - udev rules are likely not available in the container.
+    # if we need hotadd support in the container then we need to copy the rules over to /.tether
+    if [[ "${UDEV_PID}" != "" ]]; then
+        kill ${UDEV_PID}
+    fi
 
     echo "switching to the new mount"
     if systemctl; then
-        systemctl switch-root ${MOUNTPOINT} /.tether/tether 2>&1
+        systemctl switch-root ${MOUNTPOINT} /.tether/tether >/dev/console 2>/dev/console
     elif [[ "$(readlink /usr/sbin/switch_root)" == *"toybox"* ]]; then # see https://github.com/landley/toybox/issues/91
         mount --move /sys ${MOUNTPOINT}/sys
         mount --move /proc ${MOUNTPOINT}/proc
         mount --move /dev ${MOUNTPOINT}/dev
-        exec switch_root ${MOUNTPOINT} /.tether/tether 2>&1 
+        exec switch_root ${MOUNTPOINT} /.tether/tether >/dev/console 2>/dev/console
     else
-        exec switch_root ${MOUNTPOINT} /.tether/tether 2>&1 
+        exec switch_root ${MOUNTPOINT} /.tether/tether >/dev/console 2>/dev/console
         # if successful then nothing after this point executes
-        echo "Failed to switch to the new mount"
     fi
+
+    # if we fail to switch root then restore output to the debug file and note the problem
+    err=$?
+    exec >/dev/ttyS1 2>&1
+    echo "Failed to switch to the new mount: $err"
 else
     # TODO: what do we do here? we really need to somehow report an error
     # fail hard
