Restore console logging when launching tether
The tether explicitly logs to both stdout/stderr and to the serial debug
port. This change redirects stdout/stderr to the console so that we do not
end up with duplicate lines in the serial log. The stdout/stderr are
redirected to the serial log directly during bootstrap in order to log the
initializtion script output before the switch_root to tether.

diff --git a/isos/bootstrap/bootstrap b/isos/bootstrap/bootstrap
--- a/isos/bootstrap/bootstrap
+++ b/isos/bootstrap/bootstrap
@@ -115,17 +115,21 @@ if timeout -s KILL 2m mount -t ext4 /dev/disk/by-label/containerfs ${MOUNTPOINT}
 
     echo "switching to the new mount"
     if systemctl; then
-        systemctl switch-root ${MOUNTPOINT} /.tether/tether 2>&1
+        systemctl switch-root ${MOUNTPOINT} /.tether/tether >/dev/console 2>/dev/console
     elif [[ "$(readlink /usr/sbin/switch_root)" == *"toybox"* ]]; then # see https://github.com/landley/toybox/issues/91
         mount --move /sys ${MOUNTPOINT}/sys
         mount --move /proc ${MOUNTPOINT}/proc
         mount --move /dev ${MOUNTPOINT}/dev
-        exec switch_root ${MOUNTPOINT} /.tether/tether 2>&1 
+        exec switch_root ${MOUNTPOINT} /.tether/tether >/dev/console 2>/dev/console
     else
-        exec switch_root ${MOUNTPOINT} /.tether/tether 2>&1 
+        exec switch_root ${MOUNTPOINT} /.tether/tether >/dev/console 2>/dev/console
         # if successful then nothing after this point executes
-        echo "Failed to switch to the new mount"
     fi
+
+    # if we fail to switch root then restore output to the debug file and note the problem
+    err=$?
+    exec >/dev/ttyS1 2>&1
+    echo "Failed to switch to the new mount: $err"
 else
     # TODO: what do we do here? we really need to somehow report an error
     # fail hard
